In [2]:
from pathlib import Path
import sys

import pandas as pd
from IPython.display import display


# ---------------------------------------------------------------------
# Find project root and add src/ to sys.path
# ---------------------------------------------------------------------

current_dir = Path.cwd().resolve()

# This works whether Jupyter was launched from the project root
# or from the notebooks/ directory.
if (current_dir / "src").exists():
    PROJECT_ROOT = current_dir
elif (current_dir.parent / "src").exists():
    PROJECT_ROOT = current_dir.parent
else:
    raise FileNotFoundError(
        "Project root was not found. "
        "Expected to find a 'src' directory in the current directory "
        "or its parent directory."
    )

SRC_DIR = PROJECT_ROOT / "src"

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))


# ---------------------------------------------------------------------
# Import project configuration
# ---------------------------------------------------------------------

from config import RAW_ALERTS_FILE, ANALYSIS_TIMEZONE


# ---------------------------------------------------------------------
# Load raw dataset
# ---------------------------------------------------------------------

print(f"Project root: {PROJECT_ROOT}")
print(f"Expected dataset path: {RAW_ALERTS_FILE}")
print(f"Analysis timezone: {ANALYSIS_TIMEZONE}")

try:
    df_raw = pd.read_csv(RAW_ALERTS_FILE)

except FileNotFoundError:
    print("\n❌ Dataset file was not found.")
    print("Please download the dataset and save it here:")
    print(f"   {RAW_ALERTS_FILE}")

except pd.errors.EmptyDataError:
    print("\n❌ Dataset file exists, but it is empty.")

except pd.errors.ParserError as error:
    print("\n❌ CSV parsing error:")
    print(error)

else:
    print("\n✅ Dataset loaded successfully.")
    print(f"Shape: {df_raw.shape[0]:,} rows × {df_raw.shape[1]} columns")

    print("\n" + "=" * 70)
    print("DATAFRAME INFO")
    print("=" * 70)
    df_raw.info()

    print("\n" + "=" * 70)
    print("FIRST 5 ROWS")
    print("=" * 70)
    display(df_raw.head())

    print("\n" + "=" * 70)
    print("MISSING VALUES BY COLUMN")
    print("=" * 70)
    display(
        df_raw.isnull()
        .sum()
        .sort_values(ascending=False)
        .rename("missing_values")
        .to_frame()
    )

    print("\n" + "=" * 70)
    print("UNIQUE REGION VALUES: FIRST 15 ALPHABETICALLY")
    print("=" * 70)

    if "region" in df_raw.columns:
        unique_regions = (
            df_raw["region"]
            .dropna()
            .astype(str)
            .sort_values()
            .unique()
        )

        print(f"Total unique regions: {len(unique_regions)}")
        display(pd.DataFrame({"region": unique_regions[:15]}))

        kyiv_matches = [
            region
            for region in unique_regions
            if "kyiv" in region.lower() or "kiev" in region.lower()
        ]

        print("\nPossible Kyiv-related region names:")
        print(kyiv_matches if kyiv_matches else "No Kyiv-related names found.")

    else:
        print("⚠️ Column 'region' was not found.")
        print("Available columns:")
        print(df_raw.columns.tolist())

Project root: D:\it10\PythonProject2
Expected dataset path: D:\it10\PythonProject2\data\raw\official_data_en.csv
Analysis timezone: Europe/Kyiv

❌ Dataset file was not found.
Please download the dataset and save it here:
   D:\it10\PythonProject2\data\raw\official_data_en.csv

In [3]:
import sys

print(sys.executable)
print(sys.version)

D:\it10\PythonProject2\.venv\Scripts\python.exe
3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)]

In [4]:
SRC_DIR = PROJECT_ROOT / "src"

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

print(f"Current working directory: {Path.cwd()}")
print(f"Detected project root: {PROJECT_ROOT}")
print(f"Detected src directory: {SRC_DIR}")
print(f"Does src directory exist? {SRC_DIR.exists()}")
print(f"Does config.py exist? {(SRC_DIR / 'config.py').exists()}")

assert SRC_DIR.exists(), f"src directory was not found: {SRC_DIR}"
assert (SRC_DIR / "config.py").exists(), (
    f"config.py was not found. Expected path: {SRC_DIR / 'config.py'}"
)

from config import RAW_ALERTS_FILE, ANALYSIS_TIMEZONE

Current working directory: D:\it10\PythonProject2\notebooks
Detected project root: D:\it10\PythonProject2
Detected src directory: D:\it10\PythonProject2\src
Does src directory exist? True
Does config.py exist? True

In [5]:
from config import RAW_ALERTS_FILE, ANALYSIS_TIMEZONE

print("RAW_ALERTS_FILE:", RAW_ALERTS_FILE)
print("ANALYSIS_TIMEZONE:", ANALYSIS_TIMEZONE)

RAW_ALERTS_FILE: D:\it10\PythonProject2\data\raw\official_data_en.csv
ANALYSIS_TIMEZONE: Europe/Kyiv

In [6]:
from pathlib import Path
import sys

import pandas as pd
from IPython.display import display


current_dir = Path.cwd().resolve()

if (current_dir / "src").exists():
    PROJECT_ROOT = current_dir
elif (current_dir.parent / "src").exists():
    PROJECT_ROOT = current_dir.parent
else:
    raise FileNotFoundError(
        "Project root was not found. "
        "Expected to find a 'src' directory in the current directory "
        "or its parent directory."
    )

SRC_DIR = PROJECT_ROOT / "src"

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))


print(f"Current working directory: {Path.cwd()}")
print(f"Detected project root: {PROJECT_ROOT}")
print(f"Detected src directory: {SRC_DIR}")
print(f"Does src directory exist? {SRC_DIR.exists()}")
print(f"Does config.py exist? {(SRC_DIR / 'config.py').exists()}")

assert SRC_DIR.exists(), f"src directory was not found: {SRC_DIR}"
assert (SRC_DIR / "config.py").exists(), (
    f"config.py was not found. Expected path: {SRC_DIR / 'config.py'}"
)


from config import RAW_ALERTS_FILE, ANALYSIS_TIMEZONE


print(f"\nExpected dataset path: {RAW_ALERTS_FILE}")
print(f"Analysis timezone: {ANALYSIS_TIMEZONE}")


try:
    df_raw = pd.read_csv(RAW_ALERTS_FILE)

except FileNotFoundError:
    print("\n❌ Dataset file was not found.")
    print("Please save it here:")
    print(f"   {RAW_ALERTS_FILE}")

except pd.errors.EmptyDataError:
    print("\n❌ Dataset file exists, but it is empty.")

except pd.errors.ParserError as error:
    print("\n❌ CSV parsing error:")
    print(error)

else:
    print("\n✅ Dataset loaded successfully.")
    print(f"Shape: {df_raw.shape[0]:,} rows × {df_raw.shape[1]} columns")

    print("\n" + "=" * 70)
    print("DATAFRAME INFO")
    print("=" * 70)
    df_raw.info()

    print("\n" + "=" * 70)
    print("FIRST 5 ROWS")
    print("=" * 70)
    display(df_raw.head())

    print("\n" + "=" * 70)
    print("MISSING VALUES BY COLUMN")
    print("=" * 70)
    display(
        df_raw.isnull()
        .sum()
        .sort_values(ascending=False)
        .rename("missing_values")
        .to_frame()
    )

    print("\n" + "=" * 70)
    print("UNIQUE REGION VALUES: FIRST 15 ALPHABETICALLY")
    print("=" * 70)

    if "region" in df_raw.columns:
        unique_regions = (
            df_raw["region"]
            .dropna()
            .astype(str)
            .sort_values()
            .unique()
        )

        print(f"Total unique regions: {len(unique_regions)}")
        display(pd.DataFrame({"region": unique_regions[:15]}))

        kyiv_matches = [
            region
            for region in unique_regions
            if "kyiv" in region.lower() or "kiev" in region.lower()
        ]

        print("\nPossible Kyiv-related region names:")
        print(kyiv_matches if kyiv_matches else "No Kyiv-related names found.")

    else:
        print("⚠️ Column 'region' was not found.")
        print("Available columns:")
        print(df_raw.columns.tolist())

Current working directory: D:\it10\PythonProject2\notebooks
Detected project root: D:\it10\PythonProject2
Detected src directory: D:\it10\PythonProject2\src
Does src directory exist? True
Does config.py exist? True

Expected dataset path: D:\it10\PythonProject2\data\raw\official_data_en.csv
Analysis timezone: Europe/Kyiv

✅ Dataset loaded successfully.
Shape: 272,699 rows × 7 columns

======================================================================
DATAFRAME INFO
======================================================================
<class 'pandas.DataFrame'>
RangeIndex: 272699 entries, 0 to 272698
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   oblast       272699 non-null  str
 1   raion        142646 non-null  str
 2   hromada      35298 non-null   str
 3   level        272699 non-null  str
 4   started_at   272699 non-null  str
 5   finished_at  272699 non-null  str
 6   source       272699 non-null  str
dtypes: str(7)
memory usage: 14.6 MB

======================================================================
FIRST 5 ROWS
======================================================================

,oblast,raion,hromada,level,started_at,finished_at,source
0,Vinnytska oblast,NaN,NaN,oblast,2022-03-15 16:10:34+00:00,2022-03-15 16:50:07+00:00,official
1,Zhytomyrska oblast,NaN,NaN,oblast,2022-03-15 16:11:25+00:00,2022-03-15 16:54:23+00:00,official
2,Cherkaska oblast,Umanskyi raion,Umanska terytorialna hromada,hromada,2022-03-15 16:11:50+00:00,2022-03-15 16:54:47+00:00,official
3,Mykolaivska oblast,Pervomaiskyi raion,m. Pervomaisk ta Pervomaiska terytorialna hromada,hromada,2022-03-15 16:14:46+00:00,2022-03-15 16:57:08+00:00,official
4,Kirovohradska oblast,NaN,NaN,oblast,2022-03-15 16:15:11+00:00,2022-03-15 16:54:52+00:00,official

======================================================================
MISSING VALUES BY COLUMN
======================================================================

             missing_values
hromada              237401
raion                130053
oblast                    0
level                     0
started_at                0
finished_at               0
source                    0

======================================================================
UNIQUE REGION VALUES: FIRST 15 ALPHABETICALLY
======================================================================
⚠️ Column 'region' was not found.
Available columns:
['oblast', 'raion', 'hromada', 'level', 'started_at', 'finished_at', 'source']

In [7]:
# ---------------------------------------------------------------------
# Dataset structure audit: geographic levels and oblast names
# ---------------------------------------------------------------------

df_raw = df_raw.copy()

print("=" * 70)
print("RECORDS BY GEOGRAPHIC LEVEL")
print("=" * 70)

display(
    df_raw["level"]
    .value_counts(dropna=False)
    .rename_axis("level")
    .rename("record_count")
    .to_frame()
)

print("\n" + "=" * 70)
print("UNIQUE OBLAST VALUES: FIRST 30 ALPHABETICALLY")
print("=" * 70)

unique_oblasts = (
    df_raw["oblast"]
    .dropna()
    .astype(str)
    .sort_values()
    .unique()
)

print(f"Total unique oblast values: {len(unique_oblasts)}")
display(pd.DataFrame({"oblast": unique_oblasts[:30]}))

print("\n" + "=" * 70)
print("KYIV-RELATED OBLAST VALUES")
print("=" * 70)

kyiv_matches = [
    oblast
    for oblast in unique_oblasts
    if "kyiv" in oblast.lower() or "kiev" in oblast.lower()
]

print(kyiv_matches if kyiv_matches else "No Kyiv-related oblast names found.")

print("\n" + "=" * 70)
print("OBLAST-LEVEL DATASET")
print("=" * 70)

df_oblast_preview = df_raw.loc[df_raw["level"] == "oblast"].copy()

print(f"Rows with level == 'oblast': {len(df_oblast_preview):,}")
print(f"Unique oblasts at oblast level: {df_oblast_preview['oblast'].nunique()}")

display(
    df_oblast_preview["oblast"]
    .value_counts()
    .sort_index()
    .rename_axis("oblast")
    .rename("record_count")
    .to_frame()
)

print("\n" + "=" * 70)
print("DATE RANGE IN RAW DATA")
print("=" * 70)

started_at_utc = pd.to_datetime(df_raw["started_at"], utc=True, errors="coerce")
finished_at_utc = pd.to_datetime(df_raw["finished_at"], utc=True, errors="coerce")

print(f"Minimum start time (UTC): {started_at_utc.min()}")
print(f"Maximum finish time (UTC): {finished_at_utc.max()}")

print("\nMissing timestamps after parsing:")
print(f"started_at:  {started_at_utc.isna().sum()}")
print(f"finished_at: {finished_at_utc.isna().sum()}")

======================================================================
RECORDS BY GEOGRAPHIC LEVEL
======================================================================

         record_count
level
oblast         130053
raion          107348
hromada         35298

======================================================================
UNIQUE OBLAST VALUES: FIRST 30 ALPHABETICALLY
======================================================================
Total unique oblast values: 25

                     oblast
0          Cherkaska oblast
1       Chernihivska oblast
2       Chernivetska oblast
3    Dnipropetrovska oblast
4           Donetska oblast
5   Ivano-Frankivska oblast
6         Kharkivska oblast
7         Khersonska oblast
8        Khmelnytska oblast
9      Kirovohradska oblast
10                Kyiv City
11           Kyivska oblast
12          Luhanska oblast
13           Lvivska oblast
14       Mykolaivska oblast
15            Odeska oblast
16         Poltavska oblast
17         Rivnenska oblast
18            Sumska oblast
19       Ternopilska oblast
20         Vinnytska oblast
21          Volynska oblast
22       Zakarpatska oblast
23         Zaporizka oblast
24       Zhytomyrska oblast

======================================================================
KYIV-RELATED OBLAST VALUES
======================================================================
['Kyiv City', 'Kyivska oblast']

======================================================================
OBLAST-LEVEL DATASET
======================================================================
Rows with level == 'oblast': 130,053
Unique oblasts at oblast level: 25

                         record_count
oblast
Cherkaska oblast                 4918
Chernihivska oblast              5026
Chernivetska oblast              1494
Dnipropetrovska oblast          11130
Donetska oblast                 13754
Ivano-Frankivska oblast          1484
Kharkivska oblast               13008
Khersonska oblast                7150
Khmelnytska oblast               2060
Kirovohradska oblast             6688
Kyiv City                        3959
Kyivska oblast                   3900
Luhanska oblast                     2
Lvivska oblast                   1490
Mykolaivska oblast               7362
Odeska oblast                    4822
Poltavska oblast                 7986
Rivnenska oblast                 1784
Sumska oblast                    8156
Ternopilska oblast               1684
Vinnytska oblast                 2964
Volynska oblast                  1600
Zakarpatska oblast               1328
Zaporizka oblast                13372
Zhytomyrska oblast               2932

======================================================================
DATE RANGE IN RAW DATA
======================================================================
Minimum start time (UTC): 2022-03-15 16:10:34+00:00
Maximum finish time (UTC): 2026-06-23 00:44:48+00:00

Missing timestamps after parsing:
started_at:  0
finished_at: 0

In [11]:
from config import (
    ANALYSIS_END_DATE,
    ANALYSIS_START_DATE,
    ANALYSIS_TIMEZONE,
    FORECAST_REGION,
    TARGET_GEOGRAPHIC_LEVEL,
)


# ---------------------------------------------------------------------
# Filter only oblast-level records
# ---------------------------------------------------------------------

df_oblast = (
    df_raw.loc[
        df_raw["level"].eq(TARGET_GEOGRAPHIC_LEVEL),
        ["oblast", "level", "started_at", "finished_at", "source"],
    ]
    .copy()
    .rename(columns={"oblast": "region"})
)

print("=" * 70)
print("OBLAST-LEVEL FILTER")
print("=" * 70)

print(f"Target level: {TARGET_GEOGRAPHIC_LEVEL}")
print(f"Rows after level filter: {len(df_oblast):,}")
print(f"Unique regions: {df_oblast['region'].nunique()}")

display(
    df_oblast["region"]
    .value_counts()
    .sort_index()
    .rename_axis("region")
    .rename("record_count")
    .to_frame()
)


# ---------------------------------------------------------------------
# Parse timestamps and convert UTC -> Europe/Kyiv
# ---------------------------------------------------------------------

df_oblast["started_at_utc"] = pd.to_datetime(
    df_oblast["started_at"],
    utc=True,
    errors="coerce",
)

df_oblast["finished_at_utc"] = pd.to_datetime(
    df_oblast["finished_at"],
    utc=True,
    errors="coerce",
)

df_oblast["started_at_local"] = (
    df_oblast["started_at_utc"]
    .dt.tz_convert(ANALYSIS_TIMEZONE)
)

df_oblast["finished_at_local"] = (
    df_oblast["finished_at_utc"]
    .dt.tz_convert(ANALYSIS_TIMEZONE)
)


# ---------------------------------------------------------------------
# Calculate event duration
# ---------------------------------------------------------------------

df_oblast["duration_min"] = (
    df_oblast["finished_at_utc"] - df_oblast["started_at_utc"]
).dt.total_seconds() / 60


# ---------------------------------------------------------------------
# Restrict to the selected historical analysis period
# ---------------------------------------------------------------------

analysis_start = pd.Timestamp(
    ANALYSIS_START_DATE,
    tz=ANALYSIS_TIMEZONE,
)

analysis_end_exclusive = (
    pd.Timestamp(ANALYSIS_END_DATE, tz=ANALYSIS_TIMEZONE)
    + pd.Timedelta(days=1)
)

df_analysis_preview = df_oblast.loc[
    df_oblast["started_at_local"].between(
        analysis_start,
        analysis_end_exclusive,
        inclusive="left",
    )
].copy()


# ---------------------------------------------------------------------
# Quality checks: not removing anything yet
# ---------------------------------------------------------------------

duplicate_event_count = df_analysis_preview.duplicated(
    subset=["region", "started_at_utc", "finished_at_utc"],
    keep=False,
).sum()

invalid_duration_count = (
    df_analysis_preview["duration_min"].le(0).sum()
)

missing_timestamp_count = (
    df_analysis_preview["started_at_utc"].isna().sum()
    + df_analysis_preview["finished_at_utc"].isna().sum()
)

print("\n" + "=" * 70)
print("ANALYSIS PERIOD PREVIEW")
print("=" * 70)

print(f"Analysis start: {analysis_start}")
print(f"Analysis end:   {analysis_end_exclusive}")
print(f"Rows in selected period: {len(df_analysis_preview):,}")
print(f"Regions in selected period: {df_analysis_preview['region'].nunique()}")

print("\n" + "=" * 70)
print("DATA QUALITY PREVIEW")
print("=" * 70)

print(f"Missing parsed timestamps: {missing_timestamp_count:,}")
print(f"Events with duration <= 0 minutes: {invalid_duration_count:,}")
print(f"Rows belonging to exact duplicate events: {duplicate_event_count:,}")

print("\nDuration summary, minutes:")
display(
    df_analysis_preview["duration_min"]
    .describe()
    .to_frame(name="duration_min")
)

print("\n" + "=" * 70)
print("FORECAST REGION CHECK")
print("=" * 70)

df_kyiv_preview = df_analysis_preview.loc[
    df_analysis_preview["region"].eq(FORECAST_REGION)
].copy()

print(f"Forecast region: {FORECAST_REGION}")
print(f"Number of events: {len(df_kyiv_preview):,}")
print(
    f"Date range: "
    f"{df_kyiv_preview['started_at_local'].min()} "
    f"to {df_kyiv_preview['finished_at_local'].max()}"
)

display(
    df_kyiv_preview[
        [
            "region",
            "started_at_local",
            "finished_at_local",
            "duration_min",
        ]
    ].head(10)
)

ImportError: cannot import name 'TARGET_GEOGRAPHIC_LEVEL' from 'config' (D:\it10\PythonProject2\src\config.py)

In [1]:
from config import (
    ANALYSIS_END_DATE,
    ANALYSIS_START_DATE,
    ANALYSIS_TIMEZONE,
    FORECAST_REGION,
    TARGET_GEOGRAPHIC_LEVEL,
)


# ---------------------------------------------------------------------
# Filter only oblast-level records
# ---------------------------------------------------------------------

df_oblast = (
    df_raw.loc[
        df_raw["level"].eq(TARGET_GEOGRAPHIC_LEVEL),
        ["oblast", "level", "started_at", "finished_at", "source"],
    ]
    .copy()
    .rename(columns={"oblast": "region"})
)

print("=" * 70)
print("OBLAST-LEVEL FILTER")
print("=" * 70)

print(f"Target level: {TARGET_GEOGRAPHIC_LEVEL}")
print(f"Rows after level filter: {len(df_oblast):,}")
print(f"Unique regions: {df_oblast['region'].nunique()}")

display(
    df_oblast["region"]
    .value_counts()
    .sort_index()
    .rename_axis("region")
    .rename("record_count")
    .to_frame()
)


# ---------------------------------------------------------------------
# Parse timestamps and convert UTC -> Europe/Kyiv
# ---------------------------------------------------------------------

df_oblast["started_at_utc"] = pd.to_datetime(
    df_oblast["started_at"],
    utc=True,
    errors="coerce",
)

df_oblast["finished_at_utc"] = pd.to_datetime(
    df_oblast["finished_at"],
    utc=True,
    errors="coerce",
)

df_oblast["started_at_local"] = (
    df_oblast["started_at_utc"]
    .dt.tz_convert(ANALYSIS_TIMEZONE)
)

df_oblast["finished_at_local"] = (
    df_oblast["finished_at_utc"]
    .dt.tz_convert(ANALYSIS_TIMEZONE)
)


# ---------------------------------------------------------------------
# Calculate event duration
# ---------------------------------------------------------------------

df_oblast["duration_min"] = (
    df_oblast["finished_at_utc"] - df_oblast["started_at_utc"]
).dt.total_seconds() / 60


# ---------------------------------------------------------------------
# Restrict to the selected historical analysis period
# ---------------------------------------------------------------------

analysis_start = pd.Timestamp(
    ANALYSIS_START_DATE,
    tz=ANALYSIS_TIMEZONE,
)

analysis_end_exclusive = (
    pd.Timestamp(ANALYSIS_END_DATE, tz=ANALYSIS_TIMEZONE)
    + pd.Timedelta(days=1)
)

df_analysis_preview = df_oblast.loc[
    df_oblast["started_at_local"].between(
        analysis_start,
        analysis_end_exclusive,
        inclusive="left",
    )
].copy()


# ---------------------------------------------------------------------
# Quality checks: not removing anything yet
# ---------------------------------------------------------------------

duplicate_event_count = df_analysis_preview.duplicated(
    subset=["region", "started_at_utc", "finished_at_utc"],
    keep=False,
).sum()

invalid_duration_count = (
    df_analysis_preview["duration_min"].le(0).sum()
)

missing_timestamp_count = (
    df_analysis_preview["started_at_utc"].isna().sum()
    + df_analysis_preview["finished_at_utc"].isna().sum()
)

print("\n" + "=" * 70)
print("ANALYSIS PERIOD PREVIEW")
print("=" * 70)

print(f"Analysis start: {analysis_start}")
print(f"Analysis end:   {analysis_end_exclusive}")
print(f"Rows in selected period: {len(df_analysis_preview):,}")
print(f"Regions in selected period: {df_analysis_preview['region'].nunique()}")

print("\n" + "=" * 70)
print("DATA QUALITY PREVIEW")
print("=" * 70)

print(f"Missing parsed timestamps: {missing_timestamp_count:,}")
print(f"Events with duration <= 0 minutes: {invalid_duration_count:,}")
print(f"Rows belonging to exact duplicate events: {duplicate_event_count:,}")

print("\nDuration summary, minutes:")
display(
    df_analysis_preview["duration_min"]
    .describe()
    .to_frame(name="duration_min")
)

print("\n" + "=" * 70)
print("FORECAST REGION CHECK")
print("=" * 70)

df_kyiv_preview = df_analysis_preview.loc[
    df_analysis_preview["region"].eq(FORECAST_REGION)
].copy()

print(f"Forecast region: {FORECAST_REGION}")
print(f"Number of events: {len(df_kyiv_preview):,}")
print(
    f"Date range: "
    f"{df_kyiv_preview['started_at_local'].min()} "
    f"to {df_kyiv_preview['finished_at_local'].max()}"
)

display(
    df_kyiv_preview[
        [
            "region",
            "started_at_local",
            "finished_at_local",
            "duration_min",
        ]
    ].head(10)
)

ModuleNotFoundError: No module named 'config'

In [2]:
import sys
import importlib
from pathlib import Path

# Перевіряємо, що src/ є у шляхах пошуку модулів Python.
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

import config

# Завантажуємо config.py заново з диска,
# а не використовуємо стару версію з пам'яті kernel.
importlib.reload(config)

print("Loaded config module from:")
print(config.__file__)

print("\nRequired constants:")
required_constants = [
    "ANALYSIS_START_DATE",
    "ANALYSIS_END_DATE",
    "ANALYSIS_TIMEZONE",
    "FORECAST_REGION",
    "TARGET_GEOGRAPHIC_LEVEL",
]

for constant_name in required_constants:
    print(f"{constant_name}: {hasattr(config, constant_name)}")

NameError: name 'SRC_DIR' is not defined

In [3]:
from pathlib import Path
import sys
import importlib


# ---------------------------------------------------------------
# Find the project root from the current notebook location
# ---------------------------------------------------------------

current_dir = Path.cwd().resolve()

if (current_dir / "src").exists():
    PROJECT_ROOT = current_dir
elif (current_dir.parent / "src").exists():
    PROJECT_ROOT = current_dir.parent
else:
    raise FileNotFoundError(
        "Project root was not found. "
        "Expected a 'src' folder in the current directory or its parent."
    )

SRC_DIR = PROJECT_ROOT / "src"
CONFIG_FILE = SRC_DIR / "config.py"

print(f"Current working directory: {current_dir}")
print(f"Project root: {PROJECT_ROOT}")
print(f"src directory: {SRC_DIR}")
print(f"config.py path: {CONFIG_FILE}")
print(f"Does src exist? {SRC_DIR.exists()}")
print(f"Does config.py exist? {CONFIG_FILE.exists()}")


# ---------------------------------------------------------------
# Add src/ to Python module search path
# ---------------------------------------------------------------

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))


# ---------------------------------------------------------------
# Load the newest saved version of config.py
# ---------------------------------------------------------------

import config
importlib.reload(config)

print("\nLoaded config module from:")
print(config.__file__)

print("\nRequired constants:")
required_constants = [
    "ANALYSIS_START_DATE",
    "ANALYSIS_END_DATE",
    "ANALYSIS_TIMEZONE",
    "FORECAST_REGION",
    "TARGET_GEOGRAPHIC_LEVEL",
]

for constant_name in required_constants:
    exists = hasattr(config, constant_name)
    value = getattr(config, constant_name, "NOT FOUND")
    print(f"{constant_name}: {exists} | value = {value}")

Current working directory: D:\it10\PythonProject2\notebooks
Project root: D:\it10\PythonProject2
src directory: D:\it10\PythonProject2\src
config.py path: D:\it10\PythonProject2\src\config.py
Does src exist? True
Does config.py exist? True

Loaded config module from:
D:\it10\PythonProject2\src\config.py

Required constants:
ANALYSIS_START_DATE: True | value = 2022-03-15
ANALYSIS_END_DATE: True | value = 2025-11-30
ANALYSIS_TIMEZONE: True | value = Europe/Kyiv
FORECAST_REGION: True | value = Kyiv City
TARGET_GEOGRAPHIC_LEVEL: True | value = oblast

In [8]:
# =====================================================================
# 01_data_audit.ipynb
# Historical Time Series Analysis of Air Raid Alerts in Ukraine
# Step 1: Initial data loading and audit
# =====================================================================

from pathlib import Path
import sys
import importlib

import pandas as pd
from IPython.display import display


# ---------------------------------------------------------------------
# 1. Find the project root and the src/ directory
# ---------------------------------------------------------------------

current_dir = Path.cwd().resolve()

# The notebook is expected to run either from:
# - project_root/
# - project_root/notebooks/
if (current_dir / "src").exists():
    PROJECT_ROOT = current_dir

elif (current_dir.parent / "src").exists():
    PROJECT_ROOT = current_dir.parent

else:
    raise FileNotFoundError(
        "Project root was not found.\n"
        "Expected to find a folder named 'src' in the current directory "
        "or in its parent directory.\n"
        f"Current working directory: {current_dir}"
    )

SRC_DIR = PROJECT_ROOT / "src"
CONFIG_FILE = SRC_DIR / "config.py"

print("=" * 78)
print("PROJECT PATH CHECK")
print("=" * 78)

print(f"Current working directory: {current_dir}")
print(f"Detected project root:    {PROJECT_ROOT}")
print(f"Detected src directory:   {SRC_DIR}")
print(f"Expected config.py path:  {CONFIG_FILE}")
print(f"Does src directory exist? {SRC_DIR.exists()}")
print(f"Does config.py exist?     {CONFIG_FILE.exists()}")

if not CONFIG_FILE.exists():
    raise FileNotFoundError(
        "config.py was not found.\n"
        f"Expected path: {CONFIG_FILE}"
    )


# ---------------------------------------------------------------------
# 2. Add src/ to Python import paths and reload config.py
# ---------------------------------------------------------------------

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

# Remove a possible old version of config from Jupyter memory.
# This is useful when config.py was edited during notebook development.
if "config" in sys.modules:
    del sys.modules["config"]

importlib.invalidate_caches()

import config

print("\n" + "=" * 78)
print("CONFIG CHECK")
print("=" * 78)

print(f"Loaded config module from: {config.__file__}")

required_constants = [
    "RAW_ALERTS_FILE",
    "ANALYSIS_START_DATE",
    "ANALYSIS_END_DATE",
    "ANALYSIS_TIMEZONE",
    "TARGET_GEOGRAPHIC_LEVEL",
    "FORECAST_REGION",
    "SELECTED_REGIONS",
]

missing_constants = []

for constant_name in required_constants:
    if hasattr(config, constant_name):
        print(f"{constant_name}: {getattr(config, constant_name)}")
    else:
        missing_constants.append(constant_name)
        print(f"{constant_name}: NOT FOUND")

if missing_constants:
    raise AttributeError(
        "The following constants are missing in src/config.py:\n"
        f"{missing_constants}"
    )

# Copy values from config.py into notebook variables.
RAW_ALERTS_FILE = config.RAW_ALERTS_FILE
ANALYSIS_START_DATE = config.ANALYSIS_START_DATE
ANALYSIS_END_DATE = config.ANALYSIS_END_DATE
ANALYSIS_TIMEZONE = config.ANALYSIS_TIMEZONE
TARGET_GEOGRAPHIC_LEVEL = config.TARGET_GEOGRAPHIC_LEVEL
FORECAST_REGION = config.FORECAST_REGION
SELECTED_REGIONS = config.SELECTED_REGIONS


# ---------------------------------------------------------------------
# 3. Load the raw CSV dataset
# ---------------------------------------------------------------------

print("\n" + "=" * 78)
print("RAW DATASET LOADING")
print("=" * 78)

print(f"Expected dataset path: {RAW_ALERTS_FILE}")

try:
    df_raw = pd.read_csv(RAW_ALERTS_FILE)

except FileNotFoundError:
    print("\n❌ Dataset file was not found.")
    print("Save the file at this path:")
    print(f"   {RAW_ALERTS_FILE}")
    raise

except pd.errors.EmptyDataError:
    print("\n❌ The dataset file exists, but it is empty.")
    raise

except pd.errors.ParserError as error:
    print("\n❌ CSV parsing error:")
    print(error)
    raise

else:
    print("\n✅ Dataset loaded successfully.")
    print(f"Shape: {df_raw.shape[0]:,} rows × {df_raw.shape[1]} columns")


# ---------------------------------------------------------------------
# 4. Basic audit of raw data
# ---------------------------------------------------------------------

print("\n" + "=" * 78)
print("RAW DATAFRAME INFO")
print("=" * 78)

df_raw.info()

print("\n" + "=" * 78)
print("FIRST 5 ROWS")
print("=" * 78)

display(df_raw.head())

print("\n" + "=" * 78)
print("MISSING VALUES BY COLUMN")
print("=" * 78)

display(
    df_raw.isnull()
    .sum()
    .sort_values(ascending=False)
    .rename("missing_values")
    .to_frame()
)

print("\n" + "=" * 78)
print("RAW DATA COLUMNS")
print("=" * 78)

print(df_raw.columns.tolist())


# ---------------------------------------------------------------------
# 5. Validate that expected source columns are present
# ---------------------------------------------------------------------

required_raw_columns = [
    "oblast",
    "raion",
    "hromada",
    "level",
    "started_at",
    "finished_at",
    "source",
]

missing_raw_columns = [
    column
    for column in required_raw_columns
    if column not in df_raw.columns
]

if missing_raw_columns:
    raise KeyError(
        "The dataset does not contain expected columns:\n"
        f"{missing_raw_columns}\n\n"
        f"Available columns:\n{df_raw.columns.tolist()}"
    )


# ---------------------------------------------------------------------
# 6. Audit geographic levels
# ---------------------------------------------------------------------

print("\n" + "=" * 78)
print("RECORDS BY GEOGRAPHIC LEVEL")
print("=" * 78)

display(
    df_raw["level"]
    .value_counts(dropna=False)
    .rename_axis("level")
    .rename("record_count")
    .to_frame()
)

print("\n" + "=" * 78)
print("UNIQUE OBLAST VALUES: ALPHABETICALLY")
print("=" * 78)

unique_oblasts = (
    df_raw["oblast"]
    .dropna()
    .astype(str)
    .sort_values()
    .unique()
)

print(f"Total unique oblast values: {len(unique_oblasts)}")

display(
    pd.DataFrame(
        {
            "oblast": unique_oblasts
        }
    )
)

print("\n" + "=" * 78)
print("KYIV-RELATED OBLAST VALUES")
print("=" * 78)

kyiv_matches = [
    oblast
    for oblast in unique_oblasts
    if "kyiv" in oblast.lower() or "kiev" in oblast.lower()
]

print(kyiv_matches if kyiv_matches else "No Kyiv-related oblast names found.")


# ---------------------------------------------------------------------
# 7. Filter only oblast-level records
# ---------------------------------------------------------------------

df_oblast = (
    df_raw.loc[
        df_raw["level"].eq(TARGET_GEOGRAPHIC_LEVEL),
        [
            "oblast",
            "level",
            "started_at",
            "finished_at",
            "source",
        ],
    ]
    .copy()
    .rename(columns={"oblast": "region"})
)

print("\n" + "=" * 78)
print("OBLAST-LEVEL DATASET")
print("=" * 78)

print(f"Target geographic level: {TARGET_GEOGRAPHIC_LEVEL}")
print(f"Rows after level filter: {len(df_oblast):,}")
print(f"Unique regions: {df_oblast['region'].nunique()}")

display(
    df_oblast["region"]
    .value_counts()
    .sort_index()
    .rename_axis("region")
    .rename("record_count")
    .to_frame()
)


# ---------------------------------------------------------------------
# 8. Parse timestamps and convert UTC -> Europe/Kyiv
# ---------------------------------------------------------------------

df_oblast["started_at_utc"] = pd.to_datetime(
    df_oblast["started_at"],
    utc=True,
    errors="coerce",
)

df_oblast["finished_at_utc"] = pd.to_datetime(
    df_oblast["finished_at"],
    utc=True,
    errors="coerce",
)

df_oblast["started_at_local"] = (
    df_oblast["started_at_utc"]
    .dt.tz_convert(ANALYSIS_TIMEZONE)
)

df_oblast["finished_at_local"] = (
    df_oblast["finished_at_utc"]
    .dt.tz_convert(ANALYSIS_TIMEZONE)
)


# ---------------------------------------------------------------------
# 9. Calculate duration for every alert event
# ---------------------------------------------------------------------

df_oblast["duration_min"] = (
    df_oblast["finished_at_utc"]
    - df_oblast["started_at_utc"]
).dt.total_seconds() / 60


# ---------------------------------------------------------------------
# 10. Restrict the data to the MVP analysis period
# ---------------------------------------------------------------------

analysis_start = pd.Timestamp(
    ANALYSIS_START_DATE,
    tz=ANALYSIS_TIMEZONE,
)

analysis_end_exclusive = (
    pd.Timestamp(
        ANALYSIS_END_DATE,
        tz=ANALYSIS_TIMEZONE,
    )
    + pd.Timedelta(days=1)
)

period_mask = (
    df_oblast["started_at_local"].ge(analysis_start)
    & df_oblast["started_at_local"].lt(analysis_end_exclusive)
)

df_analysis_preview = df_oblast.loc[period_mask].copy()

print("\n" + "=" * 78)
print("ANALYSIS PERIOD PREVIEW")
print("=" * 78)

print(f"Analysis start: {analysis_start}")
print(f"Analysis end:   {analysis_end_exclusive}")
print(f"Rows in selected period: {len(df_analysis_preview):,}")
print(f"Regions in selected period: {df_analysis_preview['region'].nunique()}")

print("\nDate range after filtering:")
print(f"Minimum local start: {df_analysis_preview['started_at_local'].min()}")
print(f"Maximum local finish: {df_analysis_preview['finished_at_local'].max()}")


# ---------------------------------------------------------------------
# 11. Primary data-quality checks
# ---------------------------------------------------------------------

missing_started_at_count = df_analysis_preview["started_at_utc"].isna().sum()
missing_finished_at_count = df_analysis_preview["finished_at_utc"].isna().sum()

invalid_duration_count = (
    df_analysis_preview["duration_min"]
    .le(0)
    .sum()
)

duplicate_event_rows_count = (
    df_analysis_preview.duplicated(
        subset=[
            "region",
            "started_at_utc",
            "finished_at_utc",
        ],
        keep=False,
    )
    .sum()
)

print("\n" + "=" * 78)
print("DATA QUALITY PREVIEW")
print("=" * 78)

print(f"Missing parsed started_at timestamps:  {missing_started_at_count:,}")
print(f"Missing parsed finished_at timestamps: {missing_finished_at_count:,}")
print(f"Events with duration <= 0 minutes:     {invalid_duration_count:,}")
print(f"Rows belonging to exact duplicates:     {duplicate_event_rows_count:,}")

print("\nDuration summary, minutes:")
display(
    df_analysis_preview["duration_min"]
    .describe()
    .to_frame(name="duration_min")
)


# ---------------------------------------------------------------------
# 12. Check the selected regions from config.py
# ---------------------------------------------------------------------

print("\n" + "=" * 78)
print("SELECTED REGIONS CHECK")
print("=" * 78)

available_regions = set(df_analysis_preview["region"].unique())

selected_regions_status = pd.DataFrame(
    {
        "region": SELECTED_REGIONS,
        "exists_in_analysis_data": [
            region in available_regions
            for region in SELECTED_REGIONS
        ],
    }
)

display(selected_regions_status)


# ---------------------------------------------------------------------
# 13. Check the forecast region: Kyiv City
# ---------------------------------------------------------------------

df_kyiv_preview = df_analysis_preview.loc[
    df_analysis_preview["region"].eq(FORECAST_REGION)
].copy()

print("\n" + "=" * 78)
print("FORECAST REGION CHECK")
print("=" * 78)

print(f"Forecast region: {FORECAST_REGION}")
print(f"Number of events: {len(df_kyiv_preview):,}")

if df_kyiv_preview.empty:
    print("\n⚠️ No records were found for the forecast region.")
    print("Check FORECAST_REGION in src/config.py.")

else:
    print(
        "Date range:\n"
        f"  Start: {df_kyiv_preview['started_at_local'].min()}\n"
        f"  End:   {df_kyiv_preview['finished_at_local'].max()}"
    )

    display(
        df_kyiv_preview[
            [
                "region",
                "started_at_local",
                "finished_at_local",
                "duration_min",
            ]
        ].head(10)
    )


# ---------------------------------------------------------------------
# 14. Keep a compact working preview for the next notebook steps
# ---------------------------------------------------------------------

print("\n" + "=" * 78)
print("WORKING DATAFRAME PREVIEW")
print("=" * 78)

display(
    df_analysis_preview[
        [
            "region",
            "started_at_utc",
            "finished_at_utc",
            "started_at_local",
            "finished_at_local",
            "duration_min",
        ]
    ].head()
)


# =====================================================================
# Duplicate-event investigation
# =====================================================================

duplicate_key_columns = [
    "region",
    "started_at_utc",
    "finished_at_utc",
]

# Розмір кожної групи подій із однаковими region/start/end.
event_group_sizes = (
    df_analysis_preview
    .groupby(duplicate_key_columns, dropna=False)
    .size()
    .rename("copies")
)

print("=" * 78)
print("DUPLICATE EVENT INVESTIGATION")
print("=" * 78)

print(f"Total rows in analysis dataset: {len(df_analysis_preview):,}")
print(f"Unique event groups:            {len(event_group_sizes):,}")
print(
    f"Extra duplicate rows:            "
    f"{len(df_analysis_preview) - len(event_group_sizes):,}"
)

print("\nDistribution of copies per event:")
display(
    event_group_sizes
    .value_counts()
    .sort_index()
    .rename_axis("copies_per_event")
    .rename("number_of_event_groups")
    .to_frame()
)

# Отримуємо лише події, які повторюються.
duplicate_groups = (
    event_group_sizes[event_group_sizes > 1]
    .reset_index()
    .sort_values(
        by=["copies", "region", "started_at_utc"],
        ascending=[False, True, True],
    )
)

print("\nNumber of duplicated event groups:")
print(f"{len(duplicate_groups):,}")

print("\nFirst 10 duplicated event keys:")
display(duplicate_groups.head(10))

# Вибираємо перші кілька дублікатів для ручної перевірки.
sample_duplicate_keys = duplicate_groups.head(5)[duplicate_key_columns]

sample_duplicate_rows = (
    df_analysis_preview
    .merge(
        sample_duplicate_keys,
        on=duplicate_key_columns,
        how="inner",
    )
    .sort_values(duplicate_key_columns)
)

print("\n" + "=" * 78)
print("SAMPLE DUPLICATE ROWS FROM WORKING DATASET")
print("=" * 78)

display(
    sample_duplicate_rows[
        [
            "region",
            "level",
            "started_at",
            "finished_at",
            "source",
            "started_at_utc",
            "finished_at_utc",
            "duration_min",
        ]
    ]
)

# Перевіряємо оригінальні колонки raw CSV для тих самих рядків.
# Це допоможе встановити, чи дублікати відрізнялися raion або hromada.
sample_original_indices = sample_duplicate_rows.index.unique()

print("\n" + "=" * 78)
print("SAME ROWS IN ORIGINAL RAW DATASET")
print("=" * 78)

display(
    df_raw.loc[
        sample_original_indices,
        [
            "oblast",
            "raion",
            "hromada",
            "level",
            "started_at",
            "finished_at",
            "source",
        ],
    ]
)


df_clean = df_analysis_preview.drop_duplicates(
    subset=[
        "region",
        "started_at_utc",
        "finished_at_utc",
    ]
).copy()

==============================================================================
PROJECT PATH CHECK
==============================================================================
Current working directory: D:\it10\PythonProject2\notebooks
Detected project root:    D:\it10\PythonProject2
Detected src directory:   D:\it10\PythonProject2\src
Expected config.py path:  D:\it10\PythonProject2\src\config.py
Does src directory exist? True
Does config.py exist?     True

==============================================================================
CONFIG CHECK
==============================================================================
Loaded config module from: D:\it10\PythonProject2\src\config.py
RAW_ALERTS_FILE: D:\it10\PythonProject2\data\raw\official_data_en.csv
ANALYSIS_START_DATE: 2022-03-15
ANALYSIS_END_DATE: 2025-11-30
ANALYSIS_TIMEZONE: Europe/Kyiv
TARGET_GEOGRAPHIC_LEVEL: oblast
FORECAST_REGION: Kyiv City
SELECTED_REGIONS: ['Kyiv City', 'Lviv Oblast', 'Odesa Oblast', 'Kharkiv Oblast', 'Dnipropetrovsk Oblast']

==============================================================================
RAW DATASET LOADING
==============================================================================
Expected dataset path: D:\it10\PythonProject2\data\raw\official_data_en.csv

✅ Dataset loaded successfully.
Shape: 272,699 rows × 7 columns

==============================================================================
RAW DATAFRAME INFO
==============================================================================
<class 'pandas.DataFrame'>
RangeIndex: 272699 entries, 0 to 272698
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   oblast       272699 non-null  str
 1   raion        142646 non-null  str
 2   hromada      35298 non-null   str
 3   level        272699 non-null  str
 4   started_at   272699 non-null  str
 5   finished_at  272699 non-null  str
 6   source       272699 non-null  str
dtypes: str(7)
memory usage: 14.6 MB

==============================================================================
FIRST 5 ROWS
==============================================================================

,oblast,raion,hromada,level,started_at,finished_at,source
0,Vinnytska oblast,NaN,NaN,oblast,2022-03-15 16:10:34+00:00,2022-03-15 16:50:07+00:00,official
1,Zhytomyrska oblast,NaN,NaN,oblast,2022-03-15 16:11:25+00:00,2022-03-15 16:54:23+00:00,official
2,Cherkaska oblast,Umanskyi raion,Umanska terytorialna hromada,hromada,2022-03-15 16:11:50+00:00,2022-03-15 16:54:47+00:00,official
3,Mykolaivska oblast,Pervomaiskyi raion,m. Pervomaisk ta Pervomaiska terytorialna hromada,hromada,2022-03-15 16:14:46+00:00,2022-03-15 16:57:08+00:00,official
4,Kirovohradska oblast,NaN,NaN,oblast,2022-03-15 16:15:11+00:00,2022-03-15 16:54:52+00:00,official

==============================================================================
MISSING VALUES BY COLUMN
==============================================================================

             missing_values
hromada              237401
raion                130053
oblast                    0
level                     0
started_at                0
finished_at               0
source                    0

==============================================================================
RAW DATA COLUMNS
==============================================================================
['oblast', 'raion', 'hromada', 'level', 'started_at', 'finished_at', 'source']

==============================================================================
RECORDS BY GEOGRAPHIC LEVEL
==============================================================================

         record_count
level
oblast         130053
raion          107348
hromada         35298

==============================================================================
UNIQUE OBLAST VALUES: ALPHABETICALLY
==============================================================================
Total unique oblast values: 25

                     oblast
0          Cherkaska oblast
1       Chernihivska oblast
2       Chernivetska oblast
3    Dnipropetrovska oblast
4           Donetska oblast
5   Ivano-Frankivska oblast
6         Kharkivska oblast
7         Khersonska oblast
8        Khmelnytska oblast
9      Kirovohradska oblast
10                Kyiv City
11           Kyivska oblast
12          Luhanska oblast
13           Lvivska oblast
14       Mykolaivska oblast
15            Odeska oblast
16         Poltavska oblast
17         Rivnenska oblast
18            Sumska oblast
19       Ternopilska oblast
20         Vinnytska oblast
21          Volynska oblast
22       Zakarpatska oblast
23         Zaporizka oblast
24       Zhytomyrska oblast

==============================================================================
KYIV-RELATED OBLAST VALUES
==============================================================================
['Kyiv City', 'Kyivska oblast']

==============================================================================
OBLAST-LEVEL DATASET
==============================================================================
Target geographic level: oblast
Rows after level filter: 130,053
Unique regions: 25

                         record_count
region
Cherkaska oblast                 4918
Chernihivska oblast              5026
Chernivetska oblast              1494
Dnipropetrovska oblast          11130
Donetska oblast                 13754
Ivano-Frankivska oblast          1484
Kharkivska oblast               13008
Khersonska oblast                7150
Khmelnytska oblast               2060
Kirovohradska oblast             6688
Kyiv City                        3959
Kyivska oblast                   3900
Luhanska oblast                     2
Lvivska oblast                   1490
Mykolaivska oblast               7362
Odeska oblast                    4822
Poltavska oblast                 7986
Rivnenska oblast                 1784
Sumska oblast                    8156
Ternopilska oblast               1684
Vinnytska oblast                 2964
Volynska oblast                  1600
Zakarpatska oblast               1328
Zaporizka oblast                13372
Zhytomyrska oblast               2932

==============================================================================
ANALYSIS PERIOD PREVIEW
==============================================================================
Analysis start: 2022-03-15 00:00:00+02:00
Analysis end:   2025-12-01 00:00:00+02:00
Rows in selected period: 129,684
Regions in selected period: 25

Date range after filtering:
Minimum local start: 2022-03-15 18:10:34+02:00
Maximum local finish: 2025-11-30 00:28:58+02:00

==============================================================================
DATA QUALITY PREVIEW
==============================================================================
Missing parsed started_at timestamps:  0
Missing parsed finished_at timestamps: 0
Events with duration <= 0 minutes:     0
Rows belonging to exact duplicates:     129,684

Duration summary, minutes:

        duration_min
count  129684.000000
mean       79.684877
std       108.952952
min         0.033333
25%        26.300000
50%        40.375000
75%        90.766667
max      5273.550000

==============================================================================
SELECTED REGIONS CHECK
==============================================================================

                  region  exists_in_analysis_data
0              Kyiv City                     True
1            Lviv Oblast                    False
2           Odesa Oblast                    False
3         Kharkiv Oblast                    False
4  Dnipropetrovsk Oblast                    False

==============================================================================
FORECAST REGION CHECK
==============================================================================
Forecast region: Kyiv City
Number of events: 3,590
Date range:
  Start: 2022-03-15 18:19:20+02:00
  End:   2025-11-30 00:28:58+02:00

,region,started_at_local,finished_at_local,duration_min
11,Kyiv City,2022-03-15 18:19:20+02:00,2022-03-15 20:52:28+02:00,153.133333
36,Kyiv City,2022-03-16 01:33:47+02:00,2022-03-16 05:41:56+02:00,248.150000
62,Kyiv City,2022-03-16 06:12:47+02:00,2022-03-16 06:54:31+02:00,41.733333
63,Kyiv City,2022-03-16 07:31:53+02:00,2022-03-16 08:26:41+02:00,54.800000
67,Kyiv City,2022-03-16 09:09:47+02:00,2022-03-16 12:44:19+02:00,214.533333
95,Kyiv City,2022-03-16 13:33:24+02:00,2022-03-16 15:10:38+02:00,97.233333
124,Kyiv City,2022-03-16 17:47:13+02:00,2022-03-16 19:24:46+02:00,97.550000
148,Kyiv City,2022-03-16 22:31:22+02:00,2022-03-16 23:00:11+02:00,28.816667
158,Kyiv City,2022-03-16 23:43:17+02:00,2022-03-17 00:21:03+02:00,37.766667
162,Kyiv City,2022-03-17 03:21:29+02:00,2022-03-17 05:09:54+02:00,108.416667

==============================================================================
WORKING DATAFRAME PREVIEW
==============================================================================

,region,started_at_utc,finished_at_utc,started_at_local,finished_at_local,duration_min
0,Vinnytska oblast,2022-03-15 16:10:34+00:00,2022-03-15 16:50:07+00:00,2022-03-15 18:10:34+02:00,2022-03-15 18:50:07+02:00,39.550000
1,Zhytomyrska oblast,2022-03-15 16:11:25+00:00,2022-03-15 16:54:23+00:00,2022-03-15 18:11:25+02:00,2022-03-15 18:54:23+02:00,42.966667
4,Kirovohradska oblast,2022-03-15 16:15:11+00:00,2022-03-15 16:54:52+00:00,2022-03-15 18:15:11+02:00,2022-03-15 18:54:52+02:00,39.683333
7,Ivano-Frankivska oblast,2022-03-15 16:17:28+00:00,2022-03-15 17:14:18+00:00,2022-03-15 18:17:28+02:00,2022-03-15 19:14:18+02:00,56.833333
8,Lvivska oblast,2022-03-15 16:17:29+00:00,2022-03-15 17:16:23+00:00,2022-03-15 18:17:29+02:00,2022-03-15 19:16:23+02:00,58.900000

==============================================================================
DUPLICATE EVENT INVESTIGATION
==============================================================================
Total rows in analysis dataset: 129,684
Unique event groups:            64,842
Extra duplicate rows:            64,842

Distribution of copies per event:

                  number_of_event_groups
copies_per_event
2                                  64842

Number of duplicated event groups:
64,842

First 10 duplicated event keys:

,region,started_at_utc,finished_at_utc,copies
0,Cherkaska oblast,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,2
1,Cherkaska oblast,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,2
2,Cherkaska oblast,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,2
3,Cherkaska oblast,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,2
4,Cherkaska oblast,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,2
5,Cherkaska oblast,2022-03-19 10:06:50+00:00,2022-03-19 10:58:17+00:00,2
6,Cherkaska oblast,2022-03-20 03:25:06+00:00,2022-03-20 04:31:35+00:00,2
7,Cherkaska oblast,2022-03-21 08:43:10+00:00,2022-03-21 09:44:08+00:00,2
8,Cherkaska oblast,2022-03-21 10:47:46+00:00,2022-03-21 10:54:06+00:00,2
9,Cherkaska oblast,2022-03-21 14:15:27+00:00,2022-03-21 16:56:54+00:00,2

==============================================================================
SAMPLE DUPLICATE ROWS FROM WORKING DATASET
==============================================================================

,region,level,started_at,finished_at,source,started_at_utc,finished_at_utc,duration_min
0,Cherkaska oblast,oblast,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,official,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,232.333333
5,Cherkaska oblast,oblast,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,official,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,232.333333
1,Cherkaska oblast,oblast,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,official,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,96.683333
6,Cherkaska oblast,oblast,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,official,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,96.683333
2,Cherkaska oblast,oblast,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,official,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,0.583333
7,Cherkaska oblast,oblast,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,official,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,0.583333
3,Cherkaska oblast,oblast,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,official,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,44.283333
8,Cherkaska oblast,oblast,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,official,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,44.283333
4,Cherkaska oblast,oblast,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,official,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,39.616667
9,Cherkaska oblast,oblast,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,official,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,39.616667

==============================================================================
SAME ROWS IN ORIGINAL RAW DATASET
==============================================================================

,oblast,raion,hromada,level,started_at,finished_at,source
0,Vinnytska oblast,NaN,NaN,oblast,2022-03-15 16:10:34+00:00,2022-03-15 16:50:07+00:00,official
5,Khmelnytska oblast,Khmelnytskyi raion,m. Starokostiantyniv ta Starokostiantynivska t...,hromada,2022-03-15 16:16:00+00:00,2022-03-15 17:21:04+00:00,official
1,Zhytomyrska oblast,NaN,NaN,oblast,2022-03-15 16:11:25+00:00,2022-03-15 16:54:23+00:00,official
6,Kyivska oblast,Bilotserkivskyi raion,Skvyrska terytorialna hromada,hromada,2022-03-15 16:17:20+00:00,2022-03-15 16:55:55+00:00,official
2,Cherkaska oblast,Umanskyi raion,Umanska terytorialna hromada,hromada,2022-03-15 16:11:50+00:00,2022-03-15 16:54:47+00:00,official
7,Ivano-Frankivska oblast,NaN,NaN,oblast,2022-03-15 16:17:28+00:00,2022-03-15 17:14:18+00:00,official
3,Mykolaivska oblast,Pervomaiskyi raion,m. Pervomaisk ta Pervomaiska terytorialna hromada,hromada,2022-03-15 16:14:46+00:00,2022-03-15 16:57:08+00:00,official
8,Lvivska oblast,NaN,NaN,oblast,2022-03-15 16:17:29+00:00,2022-03-15 17:16:23+00:00,official
4,Kirovohradska oblast,NaN,NaN,oblast,2022-03-15 16:15:11+00:00,2022-03-15 16:54:52+00:00,official
9,Rivnenska oblast,NaN,NaN,oblast,2022-03-15 16:18:35+00:00,2022-03-15 17:13:47+00:00,official

In [10]:
# =====================================================================
# Duplicate-event investigation
# =====================================================================

duplicate_key_columns = [
    "region",
    "started_at_utc",
    "finished_at_utc",
]

# Розмір кожної групи подій із однаковими region/start/end.
event_group_sizes = (
    df_analysis_preview
    .groupby(duplicate_key_columns, dropna=False)
    .size()
    .rename("copies")
)

print("=" * 78)
print("DUPLICATE EVENT INVESTIGATION")
print("=" * 78)

print(f"Total rows in analysis dataset: {len(df_analysis_preview):,}")
print(f"Unique event groups:            {len(event_group_sizes):,}")
print(
    f"Extra duplicate rows:            "
    f"{len(df_analysis_preview) - len(event_group_sizes):,}"
)

print("\nDistribution of copies per event:")
display(
    event_group_sizes
    .value_counts()
    .sort_index()
    .rename_axis("copies_per_event")
    .rename("number_of_event_groups")
    .to_frame()
)

# Отримуємо лише події, які повторюються.
duplicate_groups = (
    event_group_sizes[event_group_sizes > 1]
    .reset_index()
    .sort_values(
        by=["copies", "region", "started_at_utc"],
        ascending=[False, True, True],
    )
)

print("\nNumber of duplicated event groups:")
print(f"{len(duplicate_groups):,}")

print("\nFirst 10 duplicated event keys:")
display(duplicate_groups.head(10))

# Вибираємо перші кілька дублікатів для ручної перевірки.
sample_duplicate_keys = duplicate_groups.head(5)[duplicate_key_columns]

sample_duplicate_rows = (
    df_analysis_preview
    .merge(
        sample_duplicate_keys,
        on=duplicate_key_columns,
        how="inner",
    )
    .sort_values(duplicate_key_columns)
)

print("\n" + "=" * 78)
print("SAMPLE DUPLICATE ROWS FROM WORKING DATASET")
print("=" * 78)

display(
    sample_duplicate_rows[
        [
            "region",
            "level",
            "started_at",
            "finished_at",
            "source",
            "started_at_utc",
            "finished_at_utc",
            "duration_min",
        ]
    ]
)

# Перевіряємо оригінальні колонки raw CSV для тих самих рядків.
# Це допоможе встановити, чи дублікати відрізнялися raion або hromada.
sample_original_indices = sample_duplicate_rows.index.unique()

print("\n" + "=" * 78)
print("SAME ROWS IN ORIGINAL RAW DATASET")
print("=" * 78)

display(
    df_raw.loc[
        sample_original_indices,
        [
            "oblast",
            "raion",
            "hromada",
            "level",
            "started_at",
            "finished_at",
            "source",
        ],
    ]
)

df_clean = df_analysis_preview.drop_duplicates(
    subset=[
        "region",
        "started_at_utc",
        "finished_at_utc",
    ]
).copy()

==============================================================================
DUPLICATE EVENT INVESTIGATION
==============================================================================
Total rows in analysis dataset: 129,684
Unique event groups:            64,842
Extra duplicate rows:            64,842

Distribution of copies per event:

                  number_of_event_groups
copies_per_event
2                                  64842

Number of duplicated event groups:
64,842

First 10 duplicated event keys:

,region,started_at_utc,finished_at_utc,copies
0,Cherkaska oblast,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,2
1,Cherkaska oblast,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,2
2,Cherkaska oblast,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,2
3,Cherkaska oblast,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,2
4,Cherkaska oblast,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,2
5,Cherkaska oblast,2022-03-19 10:06:50+00:00,2022-03-19 10:58:17+00:00,2
6,Cherkaska oblast,2022-03-20 03:25:06+00:00,2022-03-20 04:31:35+00:00,2
7,Cherkaska oblast,2022-03-21 08:43:10+00:00,2022-03-21 09:44:08+00:00,2
8,Cherkaska oblast,2022-03-21 10:47:46+00:00,2022-03-21 10:54:06+00:00,2
9,Cherkaska oblast,2022-03-21 14:15:27+00:00,2022-03-21 16:56:54+00:00,2

==============================================================================
SAMPLE DUPLICATE ROWS FROM WORKING DATASET
==============================================================================

,region,level,started_at,finished_at,source,started_at_utc,finished_at_utc,duration_min
0,Cherkaska oblast,oblast,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,official,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,232.333333
5,Cherkaska oblast,oblast,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,official,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,232.333333
1,Cherkaska oblast,oblast,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,official,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,96.683333
6,Cherkaska oblast,oblast,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,official,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,96.683333
2,Cherkaska oblast,oblast,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,official,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,0.583333
7,Cherkaska oblast,oblast,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,official,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,0.583333
3,Cherkaska oblast,oblast,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,official,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,44.283333
8,Cherkaska oblast,oblast,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,official,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,44.283333
4,Cherkaska oblast,oblast,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,official,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,39.616667
9,Cherkaska oblast,oblast,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,official,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,39.616667

==============================================================================
SAME ROWS IN ORIGINAL RAW DATASET
==============================================================================

,oblast,raion,hromada,level,started_at,finished_at,source
0,Vinnytska oblast,NaN,NaN,oblast,2022-03-15 16:10:34+00:00,2022-03-15 16:50:07+00:00,official
5,Khmelnytska oblast,Khmelnytskyi raion,m. Starokostiantyniv ta Starokostiantynivska t...,hromada,2022-03-15 16:16:00+00:00,2022-03-15 17:21:04+00:00,official
1,Zhytomyrska oblast,NaN,NaN,oblast,2022-03-15 16:11:25+00:00,2022-03-15 16:54:23+00:00,official
6,Kyivska oblast,Bilotserkivskyi raion,Skvyrska terytorialna hromada,hromada,2022-03-15 16:17:20+00:00,2022-03-15 16:55:55+00:00,official
2,Cherkaska oblast,Umanskyi raion,Umanska terytorialna hromada,hromada,2022-03-15 16:11:50+00:00,2022-03-15 16:54:47+00:00,official
7,Ivano-Frankivska oblast,NaN,NaN,oblast,2022-03-15 16:17:28+00:00,2022-03-15 17:14:18+00:00,official
3,Mykolaivska oblast,Pervomaiskyi raion,m. Pervomaisk ta Pervomaiska terytorialna hromada,hromada,2022-03-15 16:14:46+00:00,2022-03-15 16:57:08+00:00,official
8,Lvivska oblast,NaN,NaN,oblast,2022-03-15 16:17:29+00:00,2022-03-15 17:16:23+00:00,official
4,Kirovohradska oblast,NaN,NaN,oblast,2022-03-15 16:15:11+00:00,2022-03-15 16:54:52+00:00,official
9,Rivnenska oblast,NaN,NaN,oblast,2022-03-15 16:18:35+00:00,2022-03-15 17:13:47+00:00,official

In [12]:
# =====================================================================
# Duplicate-event investigation
# =====================================================================

duplicate_key_columns = [
    "region",
    "started_at_utc",
    "finished_at_utc",
]

event_group_sizes = (
    df_analysis_preview
    .groupby(duplicate_key_columns, dropna=False)
    .size()
    .rename("copies")
)

print("=" * 78)
print("DUPLICATE EVENT INVESTIGATION")
print("=" * 78)

print(f"Total rows in analysis dataset: {len(df_analysis_preview):,}")
print(f"Unique event groups:            {len(event_group_sizes):,}")
print(
    f"Extra duplicate rows:            "
    f"{len(df_analysis_preview) - len(event_group_sizes):,}"
)

print("\nDistribution of copies per event:")
display(
    event_group_sizes
    .value_counts()
    .sort_index()
    .rename_axis("copies_per_event")
    .rename("number_of_event_groups")
    .to_frame()
)

duplicate_groups = (
    event_group_sizes[event_group_sizes > 1]
    .reset_index()
    .sort_values(
        by=["copies", "region", "started_at_utc"],
        ascending=[False, True, True],
    )
)

print("\nNumber of duplicated event groups:")
print(f"{len(duplicate_groups):,}")

print("\nFirst 10 duplicated event keys:")
display(duplicate_groups.head(10))

sample_duplicate_keys = duplicate_groups.head(5)[duplicate_key_columns]

sample_duplicate_rows = (
    df_analysis_preview
    .reset_index(names="original_index")
    .merge(
        sample_duplicate_keys,
        on=duplicate_key_columns,
        how="inner",
    )
    .sort_values(duplicate_key_columns)
)

print("\n" + "=" * 78)
print("SAMPLE DUPLICATE ROWS FROM WORKING DATASET")
print("=" * 78)

display(
    sample_duplicate_rows[
        [
            "original_index",
            "region",
            "level",
            "started_at",
            "finished_at",
            "source",
            "started_at_utc",
            "finished_at_utc",
            "duration_min",
        ]
    ]
)

print("\n" + "=" * 78)
print("SAME ROWS IN ORIGINAL RAW DATASET")
print("=" * 78)

sample_original_indices = sample_duplicate_rows["original_index"].unique()

display(
    df_raw.loc[
        sample_original_indices,
        [
            "oblast",
            "raion",
            "hromada",
            "level",
            "started_at",
            "finished_at",
            "source",
        ],
    ]
)

# =====================================================================
# Deduplication preview: one row = one oblast-level alert event
# =====================================================================

EVENT_KEY_COLUMNS = [
    "region",
    "started_at_utc",
    "finished_at_utc",
    "source",
]

rows_before_deduplication = len(df_analysis_preview)

# Count groups before removing duplicate event copies.
event_group_sizes_check = (
    df_analysis_preview
    .groupby(EVENT_KEY_COLUMNS, dropna=False)
    .size()
    .rename("copies")
)

# Keep the first occurrence of each oblast-level event.
df_cleaned_preview = (
    df_analysis_preview
    .drop_duplicates(
        subset=EVENT_KEY_COLUMNS,
        keep="first",
    )
    .sort_values(
        by=["region", "started_at_utc", "finished_at_utc"],
    )
    .reset_index(drop=True)
)

rows_after_deduplication = len(df_cleaned_preview)
rows_removed_as_duplicates = (
    rows_before_deduplication - rows_after_deduplication
)

remaining_duplicate_rows = (
    df_cleaned_preview
    .duplicated(
        subset=EVENT_KEY_COLUMNS,
        keep=False,
    )
    .sum()
)

kyiv_events_before = (
    df_analysis_preview["region"]
    .eq(FORECAST_REGION)
    .sum()
)

kyiv_events_after = (
    df_cleaned_preview["region"]
    .eq(FORECAST_REGION)
    .sum()
)

print("=" * 78)
print("DEDUPLICATION PREVIEW")
print("=" * 78)

print(f"Rows before removing duplicates: {rows_before_deduplication:,}")
print(f"Rows after removing duplicates:  {rows_after_deduplication:,}")
print(f"Rows removed as duplicates:      {rows_removed_as_duplicates:,}")
print(f"Remaining duplicated event rows: {remaining_duplicate_rows:,}")

print("\nDuplicate-group distribution before cleaning:")
display(
    event_group_sizes_check
    .value_counts()
    .sort_index()
    .rename_axis("copies_per_event")
    .rename("number_of_event_groups")
    .to_frame()
)

print("\n" + "=" * 78)
print("FORECAST REGION AFTER DEDUPLICATION")
print("=" * 78)

print(f"Forecast region: {FORECAST_REGION}")
print(f"Events before deduplication: {kyiv_events_before:,}")
print(f"Events after deduplication:  {kyiv_events_after:,}")

print("\n" + "=" * 78)
print("CLEANED DATA PREVIEW")
print("=" * 78)

display(
    df_cleaned_preview[
        [
            "region",
            "started_at_local",
            "finished_at_local",
            "duration_min",
            "source",
        ]
    ].head(10)
)

print("\n" + "=" * 78)
print("CLEANING ASSERTIONS")
print("=" * 78)

assert rows_after_deduplication == len(event_group_sizes_check), (
    "The number of rows after deduplication does not match "
    "the number of unique event groups."
)

assert remaining_duplicate_rows == 0, (
    "Duplicate event rows still remain after deduplication."
)

assert (df_cleaned_preview["duration_min"] > 0).all(), (
    "Non-positive durations are present in the cleaned dataset."
)

print("✅ All cleaning checks passed successfully.")

==============================================================================
DUPLICATE EVENT INVESTIGATION
==============================================================================
Total rows in analysis dataset: 129,684
Unique event groups:            64,842
Extra duplicate rows:            64,842

Distribution of copies per event:

                  number_of_event_groups
copies_per_event
2                                  64842

Number of duplicated event groups:
64,842

First 10 duplicated event keys:

,region,started_at_utc,finished_at_utc,copies
0,Cherkaska oblast,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,2
1,Cherkaska oblast,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,2
2,Cherkaska oblast,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,2
3,Cherkaska oblast,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,2
4,Cherkaska oblast,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,2
5,Cherkaska oblast,2022-03-19 10:06:50+00:00,2022-03-19 10:58:17+00:00,2
6,Cherkaska oblast,2022-03-20 03:25:06+00:00,2022-03-20 04:31:35+00:00,2
7,Cherkaska oblast,2022-03-21 08:43:10+00:00,2022-03-21 09:44:08+00:00,2
8,Cherkaska oblast,2022-03-21 10:47:46+00:00,2022-03-21 10:54:06+00:00,2
9,Cherkaska oblast,2022-03-21 14:15:27+00:00,2022-03-21 16:56:54+00:00,2

==============================================================================
SAMPLE DUPLICATE ROWS FROM WORKING DATASET
==============================================================================

,original_index,region,level,started_at,finished_at,source,started_at_utc,finished_at_utc,duration_min
0,50,Cherkaska oblast,oblast,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,official,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,232.333333
5,113961,Cherkaska oblast,oblast,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,official,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,232.333333
1,164,Cherkaska oblast,oblast,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,official,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,96.683333
6,114075,Cherkaska oblast,oblast,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,official,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,96.683333
2,191,Cherkaska oblast,oblast,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,official,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,0.583333
7,114102,Cherkaska oblast,oblast,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,official,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,0.583333
3,285,Cherkaska oblast,oblast,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,official,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,44.283333
8,114196,Cherkaska oblast,oblast,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,official,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,44.283333
4,298,Cherkaska oblast,oblast,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,official,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,39.616667
9,114209,Cherkaska oblast,oblast,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,official,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,39.616667

==============================================================================
SAME ROWS IN ORIGINAL RAW DATASET
==============================================================================

,oblast,raion,hromada,level,started_at,finished_at,source
50,Cherkaska oblast,NaN,NaN,oblast,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,official
113961,Cherkaska oblast,NaN,NaN,oblast,2022-03-16 00:50:06+00:00,2022-03-16 04:42:26+00:00,official
164,Cherkaska oblast,NaN,NaN,oblast,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,official
114075,Cherkaska oblast,NaN,NaN,oblast,2022-03-17 01:33:50+00:00,2022-03-17 03:10:31+00:00,official
191,Cherkaska oblast,NaN,NaN,oblast,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,official
114102,Cherkaska oblast,NaN,NaN,oblast,2022-03-17 09:16:09+00:00,2022-03-17 09:16:44+00:00,official
285,Cherkaska oblast,NaN,NaN,oblast,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,official
114196,Cherkaska oblast,NaN,NaN,oblast,2022-03-18 06:12:37+00:00,2022-03-18 06:56:54+00:00,official
298,Cherkaska oblast,NaN,NaN,oblast,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,official
114209,Cherkaska oblast,NaN,NaN,oblast,2022-03-18 08:50:19+00:00,2022-03-18 09:29:56+00:00,official

==============================================================================
DEDUPLICATION PREVIEW
==============================================================================
Rows before removing duplicates: 129,684
Rows after removing duplicates:  64,842
Rows removed as duplicates:      64,842
Remaining duplicated event rows: 0

Duplicate-group distribution before cleaning:

                  number_of_event_groups
copies_per_event
2                                  64842

==============================================================================
FORECAST REGION AFTER DEDUPLICATION
==============================================================================
Forecast region: Kyiv City
Events before deduplication: 3,590
Events after deduplication:  1,795

==============================================================================
CLEANED DATA PREVIEW
==============================================================================

,region,started_at_local,finished_at_local,duration_min,source
0,Cherkaska oblast,2022-03-16 02:50:06+02:00,2022-03-16 06:42:26+02:00,232.333333,official
1,Cherkaska oblast,2022-03-17 03:33:50+02:00,2022-03-17 05:10:31+02:00,96.683333,official
2,Cherkaska oblast,2022-03-17 11:16:09+02:00,2022-03-17 11:16:44+02:00,0.583333,official
3,Cherkaska oblast,2022-03-18 08:12:37+02:00,2022-03-18 08:56:54+02:00,44.283333,official
4,Cherkaska oblast,2022-03-18 10:50:19+02:00,2022-03-18 11:29:56+02:00,39.616667,official
5,Cherkaska oblast,2022-03-19 12:06:50+02:00,2022-03-19 12:58:17+02:00,51.450000,official
6,Cherkaska oblast,2022-03-20 05:25:06+02:00,2022-03-20 06:31:35+02:00,66.483333,official
7,Cherkaska oblast,2022-03-21 10:43:10+02:00,2022-03-21 11:44:08+02:00,60.966667,official
8,Cherkaska oblast,2022-03-21 12:47:46+02:00,2022-03-21 12:54:06+02:00,6.333333,official
9,Cherkaska oblast,2022-03-21 16:15:27+02:00,2022-03-21 18:56:54+02:00,161.450000,official

==============================================================================
CLEANING ASSERTIONS
==============================================================================
✅ All cleaning checks passed successfully.

In [13]:
# =====================================================================
# Run the reusable preprocessing script on the real dataset
# =====================================================================

import importlib
import preprocessing

importlib.reload(preprocessing)

from preprocessing import preprocess_oblast_alert_events


df_cleaned, quality_report = preprocess_oblast_alert_events(
    raw_dataframe=df_raw,
    target_geographic_level=TARGET_GEOGRAPHIC_LEVEL,
    analysis_start_date=ANALYSIS_START_DATE,
    analysis_end_date=ANALYSIS_END_DATE,
    analysis_timezone=ANALYSIS_TIMEZONE,
)

print("=" * 78)
print("REUSABLE PREPROCESSING SCRIPT RESULT")
print("=" * 78)

print(f"Cleaned dataset shape: {df_cleaned.shape}")
print(f"Unique regions: {df_cleaned['region'].nunique()}")

print("\nData quality report:")
display(quality_report)

print("\nFirst 10 cleaned events:")
display(
    df_cleaned[
        [
            "region",
            "started_at_local",
            "finished_at_local",
            "duration_min",
            "source",
        ]
    ].head(10)
)

print("\nKyiv City check:")
print(
    f"Kyiv City events after preprocessing: "
    f"{df_cleaned['region'].eq(FORECAST_REGION).sum():,}"
)

assert len(df_cleaned) == 64_842
assert df_cleaned["region"].nunique() == 25
assert (df_cleaned["duration_min"] > 0).all()
assert (
    df_cleaned.duplicated(
        subset=preprocessing.EVENT_KEY_COLUMNS,
        keep=False,
    ).sum()
    == 0
)

print("\n✅ Reusable preprocessing script works correctly.")

==============================================================================
REUSABLE PREPROCESSING SCRIPT RESULT
==============================================================================
Cleaned dataset shape: (64842, 10)
Unique regions: 25

Data quality report:

                              metric   value
0                           raw_rows  272699
1            rows_after_level_filter  130053
2     invalid_timestamp_rows_removed       0
3            rows_in_analysis_period  129684
4  nonpositive_duration_rows_removed       0
5          rows_before_deduplication  129684
6         rows_removed_as_duplicates   64842
7           rows_after_deduplication   64842
8           remaining_duplicate_rows       0
9      unique_regions_after_cleaning      25

First 10 cleaned events:

,region,started_at_local,finished_at_local,duration_min,source
0,Cherkaska oblast,2022-03-16 02:50:06+02:00,2022-03-16 06:42:26+02:00,232.333333,official
1,Cherkaska oblast,2022-03-17 03:33:50+02:00,2022-03-17 05:10:31+02:00,96.683333,official
2,Cherkaska oblast,2022-03-17 11:16:09+02:00,2022-03-17 11:16:44+02:00,0.583333,official
3,Cherkaska oblast,2022-03-18 08:12:37+02:00,2022-03-18 08:56:54+02:00,44.283333,official
4,Cherkaska oblast,2022-03-18 10:50:19+02:00,2022-03-18 11:29:56+02:00,39.616667,official
5,Cherkaska oblast,2022-03-19 12:06:50+02:00,2022-03-19 12:58:17+02:00,51.450000,official
6,Cherkaska oblast,2022-03-20 05:25:06+02:00,2022-03-20 06:31:35+02:00,66.483333,official
7,Cherkaska oblast,2022-03-21 10:43:10+02:00,2022-03-21 11:44:08+02:00,60.966667,official
8,Cherkaska oblast,2022-03-21 12:47:46+02:00,2022-03-21 12:54:06+02:00,6.333333,official
9,Cherkaska oblast,2022-03-21 16:15:27+02:00,2022-03-21 18:56:54+02:00,161.450000,official

Kyiv City check:
Kyiv City events after preprocessing: 1,795

✅ Reusable preprocessing script works correctly.

In [14]:
# =====================================================================
# Daily aggregation preview
# Split alert events across local calendar days and create daily metrics
# =====================================================================

from datetime import timedelta

import numpy as np
import pandas as pd
from IPython.display import display


# ---------------------------------------------------------------------
# 1. Check that the cleaned dataset from preprocessing exists
# ---------------------------------------------------------------------

required_variables = [
    "df_cleaned",
    "ANALYSIS_START_DATE",
    "ANALYSIS_END_DATE",
    "ANALYSIS_TIMEZONE",
    "FORECAST_REGION",
]

missing_variables = [
    variable_name
    for variable_name in required_variables
    if variable_name not in globals()
]

if missing_variables:
    raise NameError(
        "The following variables are missing from the notebook session:\n"
        f"{missing_variables}\n\n"
        "Run the preprocessing cell that creates df_cleaned first."
    )


# ---------------------------------------------------------------------
# 2. Define local analysis-period boundaries
# ---------------------------------------------------------------------

analysis_start_local = pd.Timestamp(
    ANALYSIS_START_DATE,
    tz=ANALYSIS_TIMEZONE,
)

# The end boundary is exclusive:
# 2025-12-01 00:00:00 local time is not included.
analysis_end_exclusive_local = (
    pd.Timestamp(
        ANALYSIS_END_DATE,
        tz=ANALYSIS_TIMEZONE,
    )
    + pd.DateOffset(days=1)
)

print("=" * 78)
print("DAILY AGGREGATION SETTINGS")
print("=" * 78)

print(f"Analysis start (local): {analysis_start_local}")
print(f"Analysis end (exclusive, local): {analysis_end_exclusive_local}")
print(f"Input cleaned events: {len(df_cleaned):,}")


# ---------------------------------------------------------------------
# 3. Prepare event-level data and create stable event IDs
# ---------------------------------------------------------------------

events_for_aggregation = (
    df_cleaned[
        [
            "region",
            "started_at_local",
            "finished_at_local",
            "duration_min",
        ]
    ]
    .copy()
    .reset_index(drop=True)
)

events_for_aggregation.insert(
    loc=0,
    column="event_id",
    value=events_for_aggregation.index,
)

# Count events that cross a local midnight.
cross_midnight_events = (
    events_for_aggregation["started_at_local"].dt.date
    != events_for_aggregation["finished_at_local"].dt.date
).sum()

print(f"Events spanning local midnight: {cross_midnight_events:,}")


# ---------------------------------------------------------------------
# 4. Split each event into separate local calendar-day segments
# ---------------------------------------------------------------------

def split_event_into_daily_segments(
    event_id: int,
    region: str,
    started_at_local: pd.Timestamp,
    finished_at_local: pd.Timestamp,
    period_start: pd.Timestamp,
    period_end_exclusive: pd.Timestamp,
    timezone_name: str,
) -> list[dict]:
    """
    Split one alert event into one or more pieces, one per local date.

    The event is clipped to the selected analysis period first.
    This avoids accidentally assigning time after 2025-11-30
    to the MVP analysis.
    """
    clipped_start = max(started_at_local, period_start)
    clipped_end = min(finished_at_local, period_end_exclusive)

    # Ignore events that do not overlap the selected period.
    if clipped_end <= clipped_start:
        return []

    segment_rows = []

    current_date = clipped_start.date()

    while True:
        day_start = pd.Timestamp(
            current_date,
            tz=timezone_name,
        )

        next_day_start = pd.Timestamp(
            current_date + timedelta(days=1),
            tz=timezone_name,
        )

        segment_start = max(clipped_start, day_start)
        segment_end = min(clipped_end, next_day_start)

        if segment_end > segment_start:
            segment_duration_min = (
                segment_end - segment_start
            ).total_seconds() / 60

            segment_rows.append(
                {
                    "event_id": event_id,
                    "region": region,
                    "date": pd.Timestamp(current_date),
                    "segment_start_local": segment_start,
                    "segment_end_local": segment_end,
                    "segment_duration_min": segment_duration_min,
                }
            )

        # The full event was allocated across daily segments.
        if next_day_start >= clipped_end:
            break

        current_date = current_date + timedelta(days=1)

    return segment_rows


all_segments = []

for event in events_for_aggregation.itertuples(index=False):
    event_segments = split_event_into_daily_segments(
        event_id=event.event_id,
        region=event.region,
        started_at_local=event.started_at_local,
        finished_at_local=event.finished_at_local,
        period_start=analysis_start_local,
        period_end_exclusive=analysis_end_exclusive_local,
        timezone_name=ANALYSIS_TIMEZONE,
    )

    all_segments.extend(event_segments)

event_day_segments = pd.DataFrame(all_segments)

if event_day_segments.empty:
    raise ValueError(
        "No daily segments were created. "
        "Check the date range and timestamp columns."
    )


# ---------------------------------------------------------------------
# 5. Aggregate duration and active events by region and local date
# ---------------------------------------------------------------------

daily_duration_metrics = (
    event_day_segments
    .groupby(
        ["date", "region"],
        as_index=False,
    )
    .agg(
        total_duration_min=(
            "segment_duration_min",
            "sum",
        ),
        active_alert_count=(
            "event_id",
            "nunique",
        ),
    )
)

# Count alert starts on each local day.
# This differs from active_alert_count:
# an event can be active after midnight even if it started on the day before.
daily_start_metrics = (
    events_for_aggregation
    .loc[
        events_for_aggregation["started_at_local"].ge(
            analysis_start_local
        )
        & events_for_aggregation["started_at_local"].lt(
            analysis_end_exclusive_local
        )
    ]
    .assign(
        date=lambda dataframe: (
            dataframe["started_at_local"]
            .dt.tz_localize(None)
            .dt.normalize()
        )
    )
    .groupby(
        ["date", "region"],
        as_index=False,
    )
    .agg(
        alert_start_count=(
            "event_id",
            "nunique",
        )
    )
)


# ---------------------------------------------------------------------
# 6. Create a complete date × region grid
# Days without alerts must explicitly contain zeros.
# ---------------------------------------------------------------------

analysis_dates = pd.date_range(
    start=pd.Timestamp(ANALYSIS_START_DATE),
    end=pd.Timestamp(ANALYSIS_END_DATE),
    freq="D",
)

all_regions = sorted(
    events_for_aggregation["region"].unique()
)

full_daily_grid = (
    pd.MultiIndex.from_product(
        [analysis_dates, all_regions],
        names=["date", "region"],
    )
    .to_frame(index=False)
)

daily_metrics_preview = (
    full_daily_grid
    .merge(
        daily_duration_metrics,
        on=["date", "region"],
        how="left",
    )
    .merge(
        daily_start_metrics,
        on=["date", "region"],
        how="left",
    )
)

daily_metrics_preview["total_duration_min"] = (
    daily_metrics_preview["total_duration_min"]
    .fillna(0.0)
    .astype(float)
)

daily_metrics_preview["active_alert_count"] = (
    daily_metrics_preview["active_alert_count"]
    .fillna(0)
    .astype(int)
)

daily_metrics_preview["alert_start_count"] = (
    daily_metrics_preview["alert_start_count"]
    .fillna(0)
    .astype(int)
)

daily_metrics_preview["mean_active_duration_min"] = np.where(
    daily_metrics_preview["active_alert_count"] > 0,
    daily_metrics_preview["total_duration_min"]
    / daily_metrics_preview["active_alert_count"],
    0.0,
)

daily_metrics_preview = (
    daily_metrics_preview
    .sort_values(["region", "date"])
    .reset_index(drop=True)
)


# ---------------------------------------------------------------------
# 7. Validate that duration was conserved during splitting
# ---------------------------------------------------------------------

clipped_start = events_for_aggregation["started_at_local"].where(
    events_for_aggregation["started_at_local"].ge(
        analysis_start_local
    ),
    analysis_start_local,
)

clipped_end = events_for_aggregation["finished_at_local"].where(
    events_for_aggregation["finished_at_local"].lt(
        analysis_end_exclusive_local
    ),
    analysis_end_exclusive_local,
)

expected_duration_min = (
    (clipped_end - clipped_start)
    .dt.total_seconds()
    .div(60)
    .clip(lower=0)
    .sum()
)

allocated_duration_min = (
    event_day_segments["segment_duration_min"]
    .sum()
)

duration_difference_min = (
    allocated_duration_min
    - expected_duration_min
)


# ---------------------------------------------------------------------
# 8. Quality checks
# ---------------------------------------------------------------------

duplicate_daily_rows = (
    daily_metrics_preview
    .duplicated(
        subset=["date", "region"],
        keep=False,
    )
    .sum()
)

number_of_expected_daily_rows = (
    len(analysis_dates)
    * len(all_regions)
)

print("\n" + "=" * 78)
print("DAILY AGGREGATION QUALITY CHECKS")
print("=" * 78)

print(f"Event-day segments created: {len(event_day_segments):,}")
print(f"Daily metrics rows: {len(daily_metrics_preview):,}")
print(f"Expected complete daily rows: {number_of_expected_daily_rows:,}")
print(f"Duplicate date-region rows: {duplicate_daily_rows:,}")

print(
    "\nTotal duration expected after clipping: "
    f"{expected_duration_min:,.6f} minutes"
)

print(
    "Total duration allocated to daily segments: "
    f"{allocated_duration_min:,.6f} minutes"
)

print(
    "Difference after splitting: "
    f"{duration_difference_min:.12f} minutes"
)

assert len(daily_metrics_preview) == number_of_expected_daily_rows, (
    "The daily grid is incomplete."
)

assert duplicate_daily_rows == 0, (
    "Duplicate date-region rows exist after aggregation."
)

assert np.isclose(
    allocated_duration_min,
    expected_duration_min,
    rtol=0,
    atol=1e-8,
), (
    "Duration was not conserved while splitting events "
    "across local calendar days."
)

assert (daily_metrics_preview["total_duration_min"] >= 0).all(), (
    "Negative daily durations were found."
)

print("\n✅ Daily aggregation checks passed successfully.")


# ---------------------------------------------------------------------
# 9. Display results
# ---------------------------------------------------------------------

print("\n" + "=" * 78)
print("DAILY METRICS PREVIEW")
print("=" * 78)

display(daily_metrics_preview.head(15))

print("\n" + "=" * 78)
print("KYIV CITY DAILY METRICS: FIRST 15 DAYS")
print("=" * 78)

display(
    daily_metrics_preview.loc[
        daily_metrics_preview["region"].eq(FORECAST_REGION),
        [
            "date",
            "region",
            "alert_start_count",
            "active_alert_count",
            "total_duration_min",
            "mean_active_duration_min",
        ],
    ]
    .head(15)
)

print("\n" + "=" * 78)
print("SAMPLE EVENTS THAT SPAN LOCAL MIDNIGHT")
print("=" * 78)

display(
    events_for_aggregation.loc[
        events_for_aggregation["started_at_local"].dt.date
        != events_for_aggregation["finished_at_local"].dt.date,
        [
            "event_id",
            "region",
            "started_at_local",
            "finished_at_local",
            "duration_min",
        ],
    ]
    .head(10)
)

==============================================================================
DAILY AGGREGATION SETTINGS
==============================================================================
Analysis start (local): 2022-03-15 00:00:00+02:00
Analysis end (exclusive, local): 2025-12-01 00:00:00+02:00
Input cleaned events: 64,842
Events spanning local midnight: 5,330

==============================================================================
DAILY AGGREGATION QUALITY CHECKS
==============================================================================
Event-day segments created: 70,179
Daily metrics rows: 33,925
Expected complete daily rows: 33,925
Duplicate date-region rows: 0

Total duration expected after clipping: 5,166,926.783333 minutes
Total duration allocated to daily segments: 5,166,926.783333 minutes
Difference after splitting: 0.000000000000 minutes

✅ Daily aggregation checks passed successfully.

==============================================================================
DAILY METRICS PREVIEW
==============================================================================

,date,region,total_duration_min,active_alert_count,alert_start_count,mean_active_duration_min
0,2022-03-15,Cherkaska oblast,0.000000,0,0,0.000000
1,2022-03-16,Cherkaska oblast,232.333333,1,1,232.333333
2,2022-03-17,Cherkaska oblast,97.266667,2,2,48.633333
3,2022-03-18,Cherkaska oblast,83.900000,2,2,41.950000
4,2022-03-19,Cherkaska oblast,51.450000,1,1,51.450000
5,2022-03-20,Cherkaska oblast,66.483333,1,1,66.483333
6,2022-03-21,Cherkaska oblast,228.750000,3,3,76.250000
7,2022-03-22,Cherkaska oblast,335.633333,4,4,83.908333
8,2022-03-23,Cherkaska oblast,0.000000,0,0,0.000000
9,2022-03-24,Cherkaska oblast,156.716667,3,3,52.238889
10,2022-03-25,Cherkaska oblast,297.666667,6,5,49.611111
11,2022-03-26,Cherkaska oblast,357.166667,3,3,119.055556
12,2022-03-27,Cherkaska oblast,95.966667,2,2,47.983333
13,2022-03-28,Cherkaska oblast,42.750000,2,2,21.375000
14,2022-03-29,Cherkaska oblast,277.266667,6,5,46.211111

==============================================================================
KYIV CITY DAILY METRICS: FIRST 15 DAYS
==============================================================================

,date,region,alert_start_count,active_alert_count,total_duration_min,mean_active_duration_min
13570,2022-03-15,Kyiv City,1,1,153.133333,153.133333
13571,2022-03-16,Kyiv City,8,8,799.533333,99.941667
13572,2022-03-17,Kyiv City,7,8,405.916667,50.739583
13573,2022-03-18,Kyiv City,8,8,430.333333,53.791667
13574,2022-03-19,Kyiv City,6,6,336.883333,56.147222
13575,2022-03-20,Kyiv City,5,6,395.483333,65.913889
13576,2022-03-21,Kyiv City,8,9,600.650000,66.738889
13577,2022-03-22,Kyiv City,8,9,682.516667,75.835185
13578,2022-03-23,Kyiv City,6,6,430.333333,71.722222
13579,2022-03-24,Kyiv City,6,6,294.850000,49.141667
13580,2022-03-25,Kyiv City,7,7,661.183333,94.454762
13581,2022-03-26,Kyiv City,4,5,463.083333,92.616667
13582,2022-03-27,Kyiv City,5,5,310.483333,62.096667
13583,2022-03-28,Kyiv City,6,7,473.566667,67.652381
13584,2022-03-29,Kyiv City,7,8,549.783333,68.722917

==============================================================================
SAMPLE EVENTS THAT SPAN LOCAL MIDNIGHT
==============================================================================

,event_id,region,started_at_local,finished_at_local,duration_min
16,16,Cherkaska oblast,2022-03-24 23:07:11+02:00,2022-03-25 00:32:14+02:00,85.050000
28,28,Cherkaska oblast,2022-03-28 23:58:20+03:00,2022-03-29 00:01:23+03:00,3.050000
33,33,Cherkaska oblast,2022-03-29 23:08:23+03:00,2022-03-30 00:13:24+03:00,65.016667
110,110,Cherkaska oblast,2022-04-23 23:51:43+03:00,2022-04-24 00:32:33+03:00,40.833333
156,156,Cherkaska oblast,2022-05-12 23:41:37+03:00,2022-05-13 01:12:20+03:00,90.716667
181,181,Cherkaska oblast,2022-05-22 23:58:28+03:00,2022-05-23 00:45:10+03:00,46.700000
185,185,Cherkaska oblast,2022-05-23 23:46:52+03:00,2022-05-24 00:18:47+03:00,31.916667
202,202,Cherkaska oblast,2022-05-27 23:57:48+03:00,2022-05-28 01:12:59+03:00,75.183333
232,232,Cherkaska oblast,2022-06-07 23:44:17+03:00,2022-06-08 00:13:10+03:00,28.883333
245,245,Cherkaska oblast,2022-06-12 23:50:59+03:00,2022-06-13 00:09:32+03:00,18.550000

In [15]:
# =====================================================================
# Run reusable daily aggregation script on real cleaned event data
# =====================================================================

import importlib

import config
import aggregation

importlib.reload(config)
importlib.reload(aggregation)

from aggregation import aggregate_alert_events_daily


PROCESSED_DATA_DIR = config.PROCESSED_DATA_DIR
DAILY_REGION_METRICS_FILE = config.DAILY_REGION_METRICS_FILE
DAILY_AGGREGATION_QUALITY_REPORT_FILE = (
    config.DAILY_AGGREGATION_QUALITY_REPORT_FILE
)

PROCESSED_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

daily_metrics, daily_aggregation_quality_report = (
    aggregate_alert_events_daily(
        cleaned_dataframe=df_cleaned,
        analysis_start_date=ANALYSIS_START_DATE,
        analysis_end_date=ANALYSIS_END_DATE,
        analysis_timezone=ANALYSIS_TIMEZONE,
    )
)

daily_metrics.to_csv(
    DAILY_REGION_METRICS_FILE,
    index=False,
)

daily_aggregation_quality_report.to_csv(
    DAILY_AGGREGATION_QUALITY_REPORT_FILE,
    index=False,
)

print("=" * 78)
print("REUSABLE DAILY AGGREGATION SCRIPT RESULT")
print("=" * 78)

print(f"Daily metrics shape: {daily_metrics.shape}")
print(f"Unique regions: {daily_metrics['region'].nunique()}")
print(f"Date range: {daily_metrics['date'].min()} to {daily_metrics['date'].max()}")

print("\nDaily aggregation quality report:")
display(daily_aggregation_quality_report)

print("\nFirst 15 daily rows for Kyiv City:")
display(
    daily_metrics.loc[
        daily_metrics["region"].eq(FORECAST_REGION),
        [
            "date",
            "region",
            "alert_start_count",
            "active_alert_count",
            "total_duration_min",
            "mean_active_duration_min",
        ],
    ].head(15)
)

assert len(daily_metrics) == 33_925
assert daily_metrics["region"].nunique() == 25
assert not daily_metrics.duplicated(
    subset=["date", "region"],
    keep=False,
).any()

assert (
    daily_metrics["total_duration_min"] >= 0
).all()

print("\nFiles created:")
print(f"  {DAILY_REGION_METRICS_FILE}")
print(f"  {DAILY_AGGREGATION_QUALITY_REPORT_FILE}")

print("\n✅ Reusable daily aggregation script works correctly.")

==============================================================================
REUSABLE DAILY AGGREGATION SCRIPT RESULT
==============================================================================
Daily metrics shape: (33925, 6)
Unique regions: 25
Date range: 2022-03-15 00:00:00 to 2025-11-30 00:00:00

Daily aggregation quality report:

                         metric         value
0          input_cleaned_events  6.484200e+04
1         cross_midnight_events  5.330000e+03
2    event_day_segments_created  7.017900e+04
3            daily_metrics_rows  3.392500e+04
4   expected_daily_metrics_rows  3.392500e+04
5                unique_regions  2.500000e+01
6                 analysis_days  1.357000e+03
7    duplicate_date_region_rows  0.000000e+00
8         expected_duration_min  5.166927e+06
9        allocated_duration_min  5.166927e+06
10      duration_difference_min  0.000000e+00

First 15 daily rows for Kyiv City:

,date,region,alert_start_count,active_alert_count,total_duration_min,mean_active_duration_min
13570,2022-03-15,Kyiv City,1,1,153.133333,153.133333
13571,2022-03-16,Kyiv City,8,8,799.533333,99.941667
13572,2022-03-17,Kyiv City,7,8,405.916667,50.739583
13573,2022-03-18,Kyiv City,8,8,430.333333,53.791667
13574,2022-03-19,Kyiv City,6,6,336.883333,56.147222
13575,2022-03-20,Kyiv City,5,6,395.483333,65.913889
13576,2022-03-21,Kyiv City,8,9,600.650000,66.738889
13577,2022-03-22,Kyiv City,8,9,682.516667,75.835185
13578,2022-03-23,Kyiv City,6,6,430.333333,71.722222
13579,2022-03-24,Kyiv City,6,6,294.850000,49.141667
13580,2022-03-25,Kyiv City,7,7,661.183333,94.454762
13581,2022-03-26,Kyiv City,4,5,463.083333,92.616667
13582,2022-03-27,Kyiv City,5,5,310.483333,62.096667
13583,2022-03-28,Kyiv City,6,7,473.566667,67.652381
13584,2022-03-29,Kyiv City,7,8,549.783333,68.722917

Files created:
  D:\it10\PythonProject2\data\processed\daily_region_metrics.csv
  D:\it10\PythonProject2\data\processed\daily_aggregation_quality_report.csv

✅ Reusable daily aggregation script works correctly.

In [16]:
# =====================================================================
# Save cleaned event-level dataset for EDA and forecasting
# =====================================================================

import importlib
import config

importlib.reload(config)

config.PROCESSED_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

df_cleaned.to_csv(
    config.CLEANED_ALERTS_FILE,
    index=False,
)

quality_report.to_csv(
    config.DATA_QUALITY_REPORT_FILE,
    index=False,
)

print("✅ Cleaned event-level dataset saved successfully.")
print(f"Cleaned events file: {config.CLEANED_ALERTS_FILE}")
print(f"Quality report file: {config.DATA_QUALITY_REPORT_FILE}")

assert config.CLEANED_ALERTS_FILE.exists()
assert config.DATA_QUALITY_REPORT_FILE.exists()

✅ Cleaned event-level dataset saved successfully.
Cleaned events file: D:\it10\PythonProject2\data\processed\alerts_cleaned.csv
Quality report file: D:\it10\PythonProject2\data\processed\data_quality_report.csv